### PR TITLE
[fix] refix the issue #60, was reintroduced with  3de3773

### PR DESCRIPTION
**Pull request by jgrumboe**
[fix] always use full path to binaries

### CODE REVIEW

**Comment by jgrumboe** [comment]
@LalatenduMohanty

**Comment by jgrumboe** [comment]
may someone have a look at this PR?

**Comment by pvalena** [comment]
Hi, thank you for the PR! I will test this soon.

**Comment by jgrumboe** [comment]
Hi, when do you think this PR will be merged?

**Comment by jgrumboe** [comment]
Can somebody merge this, please? (possibly @hferentschik )

**Comment by hferentschik** [comment]
So which issue is this actually adressing? Is there one? If not could you please create one describing what this is about in the first place. Also please prefix then the commit with the issue key "Issue #xyz".

**Comment by LalatenduMohanty** [comment]
I think it is https://github.com/projectatomic/adb-vagrant-registration/issues/60
@jgrumboe can you please add steps to reproduce. Honestly I am not sure how to test this PR.

**Comment by hferentschik** [comment]
> can you please add steps to reproduce. Honestly I am not sure how to test this PR.

+1 Can you maybe write a (Cucumber) test which verifies that using an existing cert works. If not, steps to reproduce this would be required.

**Comment by hferentschik** [comment]
> I think it is #60

Issue #60 is already closed and code has been merged for it. If the merged code introduced a regression, we need a new issue describing the regression and we then work against this issue to fix the regression.

**Comment by jgrumboe** [comment]
Sorry guys, I'm also confused here.
My PR doesn't introduce any new things it just corrects a problem which was fixed by the merge of #61.
But with the later merge of #59 the line 84 in rhn_register.rb was "rollbacked":
  -              cert_file_content = File.read(machine.config.registration.ca_cert)  
  +              cert_file_content = File.read(machine.config.registration.ca_cert, tmp)  

So should i only open an issue to reference here?

**Comment by hferentschik** [comment]
> So should i only open an issue to reference here?

Yes. You should create a issue for that, describing the regression and then make commits against this issue. If you are having problems about the right workflow let me know. I can help sorting it out. But basically it looks like this:

* Create the issue. Let's assume it's 1001
* Make sure your master branch is up to date. Assuming _origin_ is tracking this repository and _my-fork_ is your fork of this repository.

        $ git checkout master
        $ git pull origin master
        $ git checkout -b issue-1001
        # make your code changes
        $ git add .
        $ git commit -m "Issue #1001 <Describe what you've done>"
        $ git push my-fork HEAD

Once you have done that, create the pull request.

**Comment by jgrumboe** [comment]
ok thx, sounds reasonable.
Will do this next week, since i'm not in the office the next days.
Afterwards i will close this pull request.

**Comment by hferentschik** [comment]
> Will do this next week, since i'm not in the office the next days.

+1

**Comment by kinneyjb** [comment]
Hello, will this fix be included after 1.2.3?

$ vagrant plugin list
vagrant-openstack-provider (0.7.2)
vagrant-registration (1.2.3)

**Pull request closed without merging**
