### PR TITLE
Fixes #93. Incrementing the Version for 1.2.3 release

### LINKED ISSUE #93: Release vagrant-registration 1.2.3
We have the PR for using the vagrant-registration with http proxy settings so we should do a bug fix release.

- Run tests on Windows
- Run tests on OS X
- Run tests on Linux

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by budhrg** [comment]
@LalatenduMohanty Is this good to just bump the release version with any changes/fix/improvements? What is the purpose of it?

**Comment by LalatenduMohanty** [comment]
@budhrg it is for #93

**Comment by budhrg** [comment]
Ok @LalatenduMohanty

**Comment by budhrg** [comment]
LGTM :+1:

**Comment by hferentschik** [comment]
Would you not to the version change as part of the release? Seems very odd to increment the version like this.

**Comment by LalatenduMohanty** [comment]
@hferentschik you mean version and change log at one go?

**Comment by LalatenduMohanty** [comment]
@hferentschik Will follow https://github.com/projectatomic/vagrant-service-manager/blob/master/CONTRIBUTING.adoc#releasing  from next release

**Comment by hferentschik** [comment]
> you mean version and change log at one go?

Yes, and make a commit which makes it clear that this is the release commit. At the moment there is no telling which is this commit. Something like - _adb-vagrant-registration version=x.y.z_. The commit then includes the changelog changes, version increment (and whatever else would be needed for the actual release). 

> Will follow https://github.com/projectatomic/vagrant-service-manager/blob/master/CONTRIBUTING.adoc#releasing from next release

+1

Might be worth to sync the CONTRIBUTING guidelines. I would love to see no merge commits in this repo either ;-)

**Pull request merged**
